packages:
  # executable/launchable applications
  - 'apps/earthymaw'
  - "apps/earthytrees"
  - 'apps/curation'
  - 'apps/curation-code'
  - "apps/curation-observability"
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
