name = "Four on the Floor"
description = "Typical kick drum four on the floor beat"
total_length = 16
outputs = 1
tags = [
    "house", "trance", "edm"
]
type = "step"


[NoteToPlay]
note = "C2"

[TriggerWhen]
trigger = "every 4 steps"
fillWhen = "last 16 of 64"
fillList = [
    [0, 4, 8, 12],
    [0, 4, 8, 12, 13],
    [0, 4, 8, 12, 14],
    [0, 4, 8, 12, 15],
    [4],
    [8],
    [12],
    [4, 8],
    [8, 12],
    [4, 12],
    [4, 8, 12],
]
