name = "One Two"
description = "Two note repeating interval"
length = 4
outputs = 1
tags = [ "minimalism" ]
type = "step"

[IntervalsToPlay]
list = [1, 0, 5, 0, 1, 0, 8, 0]


[TriggerWhen]
trigger = "every 2 steps"


